### ISSUE TITLE
images from mobile device are rotated

### ISSUE THREAD

**Issue by henryhsue** [GetStream/react-file-utils#1]
The images shown on `ImagePreviewer` from my mobile device (a pixel 1 w/ latest and my friend's Pixel 3 both w/ latest Google software) are rotated incorrectly. After file is submitted to a feed, it is upright again. 

I am using the react-activity-feed (edit: for web) loaded onto a Chrome mobile browser. The camera button appears to trigger `ImageUploadButton` and `ImagePreviewer`. When I take a photo, the image shows as rotated incorrectly during the preview. However, after submitting the photo to a feed, the photo is then shown correctly upright. 

File uploads of images are file (selecting an image already taking on your phone), and appear upright on the `ImagePreviewer`. Only input from camera is affected. 

Any idea how to fix this or where I should look? 

FYI: I made some very minor css edits to my copy of react-file-utils but they shouldn't affect this. I reverted them all I think and still see this issue.

**Comment by henryhsue** [comment]
@jaapbakker88 hello, any chance you can take a peek at this?

**Comment by tschellenbach** [comment]
Jaap was sick today, it might be a few days

**Comment by jaapbakker88** [comment]
@henryhsue what version of React, React-Native are you using? Are you using our native package or our expo package? Or are you using `react-file-utils` by itself?

**Comment by henryhsue** [comment]
@jaapbakker88 I should have clarified, we are using web (react-activity-feed) on mobile devices to test an MVP.

**Comment by henryhsue** [comment]
The image orientation is only correct when a mobile phone is physically rotated 90 degrees to the left from portrait mode before taking a photo. Any other orientation is incorrect and rotates the photo (only in preview component) by the amount that that orientation is off from 90 degrees to the left. It's as if the phone used 90 degrees to the left as the upright orientation but the preview component disregarded the exif data and rotates the photo. Interestingly, photos appear upright after submitting to a feed.

**Comment by jaapbakker88** [comment]
Yeah this is an issue with the EXIF data, when the image is uploaded the data is handled and processed the way it should by our CDN, but before it's not. I'm looking into a way to read and process the images before upload as well.

**Comment by henryhsue** [comment]
Thanks for looking into it. Btw, if you need to see the error reproduced, this is the project and the camera button can be accessed after "continue with FB": https://selfiegoals.appspot.com/

**Comment by henryhsue** [comment]
@jaapbakker88, I tried using this package as a quick fix but am running into a rollup related issue. I simply installed the package into react-file-utils package. ie: 

```
cd react-activity-feed/node_modules/react-file-utils
yarn add react-fix-image-orientation
```

...then using the package in _similar_ fashion within Thumbnail.js (copying from the example from the Readme of react-fix-image-orientation:

```
import React from 'react';
import Img from 'react-fix-image-orientation
 
const MyComponent = () =>
  <Img
    src="https://github.com/recurser/exif-orientation-examples/blob/master/Portrait_8.jpg?raw=true"
    alt="A waterfall"
  />
```

And I get this error:

```
yarn run v1.16.0
$ mkdir -p dist && rollup -c

src/index.js → dist/index.js, dist/index.es.js...
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
created dist/index.js, dist/index.es.js in 5.3s

src/index.js → dist/browser.full-bundle.js...
(!) Error when using sourcemap for reporting an error: Can't resolve original location of error.
react-file-utils/node_modules/react-fix-image-orientation/lib/ExifOrientationImg.js: (7:7)
[!] Error: 'default' is not exported by commonjs-proxy:exif2css
https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-
react-file-utils/node_modules/react-fix-image-orientation/lib/ExifOrientationImg.js (7:7)
5: });
6:
7: var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();
          ^
8:
9: var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };
Error: 'default' is not exported by commonjs-proxy:exif2css
    at error (/Users/henryhsue/Work/selfiegoal/app/react-activity-feed/node_modules/rollup/dist/rollup.js:3596:30)
    at Module.error (/Users/henryhsue/Work/selfiegoal/app/react-activity-feed/node_modules/rollup/dist/rollup.js:14371:9)
    at handleMissingExport (/Users/henryhsue/Work/selfiegoal/app/react-activity-feed/node_modules/rollup/dist/rollup.js:14040:21)
    at Module.traceVariable (/Users/henryhsue/Work/selfiegoal/app/react-activity-feed/node_modules/rollup/dist/rollup.js:14472:17)
    at ModuleScope.findVariable (/Users/henryhsue/Work/selfiegoal/app/react-activity-feed/node_modules/rollup/dist/rollup.js:13804:29)
    at FunctionScope.Scope.findVariable (/Users/henryhsue/Work/selfiegoal/app/react-activity-feed/node_modules/rollup/dist/rollup.js:4194:68)
    at Scope.findVariable (/Users/henryhsue/Work/selfiegoal/app/react-activity-feed/node_modules/rollup/dist/rollup.js:4194:68)
    at Identifier$$1.bind (/Users/henryhsue/Work/selfiegoal/app/react-activity-feed/node_modules/rollup/dist/rollup.js:11156:40)
    at CallExpression.NodeBase.bind (/Users/henryhsue/Work/selfiegoal/app/react-activity-feed/node_modules/rollup/dist/rollup.js:10186:31)
    at CallExpression.bind (/Users/henryhsue/Work/selfiegoal/app/react-activity-feed/node_modules/rollup/dist/rollup.js:11268:31)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by henryhsue** [comment]
@JelteF @jaapbakker88 Is there any availability to work on this? 

I have poked around this for quite a bit but my experience w/ react and this codebase is too minimal. I've added the above package successfully (https://github.com/rricard/react-exif-orientation-img), but the EXIF data for uploaded images through `StatusUpdateForm` appears to be missing from the img src within `Thumbnail`. Do you know why this might be?

**Comment by tbarbugli** [comment]
@jaapbakker88 is taking a few days off but he will look into this next week

**Comment by henryhsue** [comment]
@tbarbugli thanks for the heads up!

**Comment by jaapbakker88** [comment]
@henryhsue yeah i've looked at that library as well but it doesnt seem to actually work in all cases, I'm trying a different solution now but it's a tricky thing to get right.

**Comment by jaapbakker88** [comment]
@henryhsue I updated `react-file-utils` to `0.3.8` and `react-activity-feed` to `0.9.21` which should resolve the issue. Could you please confirm if this is working for you?

**Comment by henryhsue** [comment]
@jaapbakker88 thank you! can confirm this works for me! good idea to use Blueimp as well.
