### ISSUE TITLE
Thumbnail component throws exception on toDataURL

### ISSUE THREAD

**Issue by DamonOehlman** [GetStream/react-file-utils#17]
Hey folks,

Just a quick one that should be pretty easy to fix hopefully.  The `Thumbnail` component throws an error when attempting to get the base64 data via the `toDataURL` call in this code block:

https://github.com/GetStream/react-file-utils/blob/master/src/components/Thumbnail.js#L67-L77

This is only triggered in cases where the image that is attempting to be thumbnailed has been sourced from a site that doesn't have the appropriate CORS settings in place. But I do expect this is reasonably common as I've seen it popping up a bit.

**Comment by jaapbakker88** [comment]
Thank you for your report, we're issuing a fix today

**Comment by jaapbakker88** [comment]
We've just released version 0.3.15 which resolves this issue.
