### ISSUE TITLE
Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by peterferguson** [GetStream/react-file-utils#36]
Using NextJS gives this error on build.

```
./node_modules/react-file-utils/dist/styles/App.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/react-file-utils/dist/index.js
```

Is there an issue with these not being imported as modules? 

If not is there a way I can get round this without reverting the version of either NextJS or Stream?

**Comment by brycefranzen** [comment]
> Using NextJS gives this error on build.
> 
> ```
> ./node_modules/react-file-utils/dist/styles/App.css
> Global CSS cannot be imported from within node_modules.
> Read more: https://nextjs.org/docs/messages/css-npm
> Location: node_modules/react-file-utils/dist/index.js
> ```
> 
> Is there an issue with these not being imported as modules?
> 
> If not is there a way I can get round this without reverting the version of either NextJS or Stream?

https://nextjs.org/docs/messages/css-npm for more details

**Comment by brycefranzen** [comment]
I found a temporary solution for anybody that encounters this: https://www.npmjs.com/package/next-remove-imports

**Comment by DanC5** [comment]
@brycefranzen @peterferguson we're working on a fix for this right now and should have something released soon, thanks!

**Comment by DanC5** [comment]
@brycefranzen @peterferguson we just made a new release of both `react-file-utils` and `stream-chat-react`, let me know if this fixes your issue, thanks!

https://github.com/GetStream/stream-chat-react/releases/tag/v6.4.1
https://github.com/GetStream/react-file-utils/releases/tag/v1.1.3

**Comment by brycefranzen** [comment]
This resolved the issue for me! Thank you!

**Comment by DanC5** [comment]
@brycefranzen great! I'm going to close this issue, but @peterferguson do reach out if you continue to have issues.
