### ISSUE TITLE
placeholder image not found

### ISSUE THREAD

**Issue by monzoor-rm** [GetStream/react-file-utils#39]
`./node_modules/react-file-utils/dist/components/Thumbnail.js
Module not found: Can't resolve '../images/placeholder-generic.png' in '/Users/monzoormo..../node_modules/react-file-utils/dist/components'`

Not working with the latest version. But v1.1.1 is fine.

**Comment by DanC5** [comment]
@monzoor-rm I'm unable to replicate this issue in other apps. Can you share details on your app's setup? Are you using Next or Meteor to serve your app?

**Comment by r0zar** [comment]
I'm also seeing this error. popped up after forking react-activity-feed and adding an new dependency.

**Comment by DanC5** [comment]
@r0zar which version do you see this error with? v1.1.4 / v1.1.3 / both?

**Comment by DanC5** [comment]
@monzoor-rm @r0zar I just made a new release that added an image processing plugin to our Rollup config, https://github.com/GetStream/react-file-utils/releases/tag/v1.1.5. I've tested this in both NextJS and regular TypeScript apps and can't replicate any issues, so please let me know how this performs on your end. Thanks.

**Comment by monzoor-rm** [comment]
@DanC5 I have updated to latest one 
![image](https://user-images.githubusercontent.com/64854078/131453749-a9e32875-3e41-4ea9-98e8-ea0dc06dc6d5.png)

Still having same issue. 

Interestingly this issue is not available in `react-file-utils 1.1.0`

**Comment by DanC5** [comment]
@monzoor-rm @r0zar our feeds developer Anton is working on patching this in `react-activity-feed`. He'll check back in once we have more information, thanks!

**Comment by DanC5** [comment]
@monzoor-rm @r0zar we just released a new version that removes this png entirely and replaces it with a React svg component. I'm going to close this issue as all should be fine since the image not longer exists, but let me know if any issues persist, thanks.
